#pragma once
//Automatically generated build count file. DO NOT EDIT MANUALLY!

#define BUILD_COUNT_ANUBIS 91
#define BUILD_COUNT_DESKTOP_EDTCHAL 3607
#define BUILD_COUNT_POCKETPC 22

#define RELEASE_COUNT_ANUBIS 0
#define RELEASE_COUNT_DESKTOP_EDTCHAL 65
#define RELEASE_COUNT_POCKETPC 0

#define BUILDCOUNT (BUILD_COUNT_ANUBIS+BUILD_COUNT_DESKTOP_EDTCHAL+BUILD_COUNT_POCKETPC)
#define RELEASECOUNT (RELEASE_COUNT_ANUBIS+RELEASE_COUNT_DESKTOP_EDTCHAL+RELEASE_COUNT_POCKETPC)
